version: '2'
services:
  eureka:
    image: huangzs/ace-center
    ports:
      - "8010:8010"
  ace-auth:
    image: huangzs/ace-auth
    ports:
      - "8020:8020"
    depends_on:
      - eureka
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8010
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_HOST=5672
  ace-admin:
    image: huangzs/ace-admin
    ports:
      - "8030:8030"
    links:
      - ace-auth
    entrypoint: ./wait-for-it.sh ace-auth:8020 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8010
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_HOST=5672
  ace-gate:
    image: huangzs/ace-gate
    ports:
      - "8000:8000"
    links:
      - ace-auth
    entrypoint: ./wait-for-it.sh ace-auth:8020 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_HOST=5672
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/var/lib/redis